version: "3.9"
services:
  rtmpserver:
    container_name: rtmpserver
    build:
      context: ./rtmpserver
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 1935:1935
    networks:
      - media-network
    volumes:
      - ./rtmpserver:/app
      - /app/node_modules

  stream_server:
    container_name: stream_server
    build:
      context: ./stream_server
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    networks:
      - media-network
    depends_on:
      - rtmpserver
    volumes:
      - ./stream_server:/app
      - /app/node_modules
    
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    networks:
      - media-network
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  media-network:
    driver: bridge

volumes:
  media-server:
  stream_server:
