version: "3.9"
services:
  media-server:
    container_name: media-server
    build:
      context: ./rtmpserver
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 1935:1935
    networks:
      - media-network

  app:
    container_name: stream_server
    build:
      context: ./stream_server
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    networks:
      - media-network
    depends_on:
      - media-server

networks:
  media-network:
    driver: bridge
